import './globals.css'
import Header from "./ui/modules/layout/templates/nav";
import Footer from "./ui/modules/layout/templates/footer";
import React from "react";

export const metadata = {
  title: 'Share',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
      <Header />
      {children}
      <Footer></Footer>
      </body>
    </html>
  )
}
